# Generated by Django 4.0.4 on 2022-07-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
