# Generated by Django 4.0.4 on 2022-08-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_profile_fb_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='images/user.png', upload_to='pics/'),
        ),
    ]
