# Generated by Django 4.0.4 on 2022-08-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_added',)},
        ),
    ]
